# Generated by Django 3.0.5 on 2020-05-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=300)),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data do Registro')),
                ('data_prazo', models.DateTimeField(verbose_name='Prazo')),
                ('data_concluido', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Categoria')),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
    ]
