# Generated by Django 3.0.5 on 2020-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro'),
        ),
    ]
