# Generated by Django 3.0.5 on 2020-06-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ramais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Frete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao_Frete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('pedido', models.CharField(blank=True, max_length=7, null=True, verbose_name='Pedido')),
                ('nota_fiscal', models.CharField(blank=True, max_length=7, null=True, verbose_name='Nota Fiscal')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC')], max_length=2, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cubagem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ramais.Empresa', verbose_name='Empresa')),
                ('frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faturamento.Tipo_Frete')),
                ('nome_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faturamento.Cliente')),
            ],
        ),
    ]
