# Generated by Django 3.0.5 on 2020-06-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_auto_20200604_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao_frete',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='cotacao_frete',
            name='nome_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faturamento.Cliente', verbose_name='Cliente'),
        ),
    ]
