# Generated by Django 3.0.7 on 2020-06-16 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=35, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'db_table': 'categoria_base',
            },
        ),
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data Registro')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Ultima Alteração')),
                ('descricao', models.TextField(max_length=1200, verbose_name='Descrição')),
                ('solucao', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Solução')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ManyToManyField(related_name='base_categoria', to='baseConhecimento.categoria', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base',
            },
        ),
    ]
